# -*- coding: utf-8 -*-
"""SE project - bio agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUUt6BTtyxwYXwrQMI35l09VslnHGJIr
"""

"""
Biology Agent for Protein Druggability Assessment
- Determines if a protein plays a key role in causing disease
- Avoids targets where blocking the protein does not affect disease outcome
"""

import requests
import json
import os

OPEN_TARGETS_URL = "https://api.platform.opentargets.org/api/v4/graphql"

def get_ensembl_id(gene_symbol: str) -> tuple:
    url = f"https://api.platform.opentargets.org/api/v4/graphql"

    query = """
    query SearchTarget($symbol: String!) {
      search(queryString: $symbol, entityNames: ["target"]) {
        hits {
          id
          name
          entity
          object {
            ... on Target {
              id
              approvedSymbol
              approvedName
            }
          }
        }
      }
    }
    """
    response = requests.post(
        url,
        json={"query": query, "variables": {"symbol": gene_symbol}},
        timeout=15
    )
    data = response.json()
    hits = data.get("data", {}).get("search", {}).get("hits", [])

    for hit in hits:
        obj = hit.get("object", {})
        if obj.get("approvedSymbol", "").upper() == gene_symbol.upper():
            return obj["id"], obj["approvedName"]

    if hits:
        obj = hits[0].get("object", {})
        return obj.get("id"), obj.get("approvedName")

    return None, None

def get_disease_associations(ensembl_id: str) -> list:
    query = """
    query GetAssociations($id: String!) {
      target(ensemblId: $id) {
        associatedDiseases(page: {index: 0, size: 200}) {
          rows {
            score
            disease {
              id
              name
            }
            datatypeScores {
              id
              score
            }
          }
        }
      }
    }
    """
    response = requests.post(
        OPEN_TARGETS_URL,
        json={"query": query, "variables": {"id": ensembl_id}},
        timeout=15
    )
    data = response.json()
    target = data.get("data", {}).get("target", {})
    rows = target.get("associatedDiseases", {}).get("rows", [])
    return rows


# -------------------------------
# FIXED DISEASE MATCH FUNCTION
# -------------------------------
def find_disease_match(associations: list, disease_query: str) -> dict:
    disease_query_lower = disease_query.lower().strip()

    best_match = None
    best_score = 0

    for row in associations:
        disease_name = row["disease"]["name"].lower().strip()

        # Strict match (substring match only)
        if disease_query_lower in disease_name or disease_name in disease_query_lower:

            if row["score"] > best_score:
                best_score = row["score"]
                best_match = row

    return best_match


def parse_evidence_types(datatype_scores: list) -> dict:
    evidence_map = {
        "genetic_association": "Genetic mutations in patients",
        "somatic_mutation":    "Somatic mutations in disease tissue",
        "known_drug":          "Existing drugs target this protein",
        "affected_pathway":    "Protein is in disease pathway",
        "literature":          "Mentioned in research papers",
        "animal_model":        "Animal knockout/overexpression studies",
        "rna_expression":      "Gene expression changes in disease",
        "text_mining":         "Text mining from publications"
    }
    parsed = {}
    for item in datatype_scores:
        label = evidence_map.get(item["id"], item["id"])
        parsed[label] = round(item["score"], 3)
    return parsed


def rule_based_assessment(overall_score: float, evidence: dict) -> dict:
    flags = []
    avoid_flags = []

    if evidence.get("Genetic mutations in patients", 0) > 0.3:
        flags.append("Strong genetic evidence: mutations found in patients")
    if evidence.get("Somatic mutations in disease tissue", 0) > 0.3:
        flags.append("Somatic mutations present - likely driver not bystander")
    if evidence.get("Existing drugs target this protein", 0) > 0.2:
        flags.append("Already a known drug target - druggability validated")
    if evidence.get("Animal knockout/overexpression studies", 0) > 0.2:
        flags.append("Animal model evidence: blocking this protein affects disease")

    if evidence.get("Genetic mutations in patients", 0) < 0.1 and \
       evidence.get("Somatic mutations in disease tissue", 0) < 0.1:
        avoid_flags.append("No genetic/somatic mutation evidence - may be bystander")
    if evidence.get("Gene expression changes in disease", 0) > 0.3 and \
       evidence.get("Genetic mutations in patients", 0) < 0.1:
        avoid_flags.append("Only expression change - likely bystander, not driver")

    if overall_score >= 0.6:
        verdict = "STRONG TARGET"
    elif overall_score >= 0.35:
        verdict = "MODERATE TARGET"
    elif overall_score >= 0.15:
        verdict = "WEAK TARGET - needs more evidence"
    else:
        verdict = "AVOID - insufficient disease link"

    return {
        "verdict": verdict,
        "overall_score": round(overall_score, 3),
        "positive_signals": flags,
        "warning_signals": avoid_flags
    }


def biology_agent(gene_symbol: str, disease_name: str):
    print(f"\n{'='*60}")
    print(f"  BIOLOGY AGENT - Druggability Assessment")
    print(f"{'='*60}")
    print(f"  Protein : {gene_symbol}")
    print(f"  Disease : {disease_name}")
    print(f"{'='*60}\n")

    print("[1/4] Looking up protein in Open Targets...")
    ensembl_id, full_name = get_ensembl_id(gene_symbol)
    if not ensembl_id:
        print(f"ERROR: Could not find '{gene_symbol}' in Open Targets.")
        return
    print(f"      Found: {gene_symbol} ({full_name}) -> {ensembl_id}")

    print("[2/4] Fetching disease associations...")
    associations = get_disease_associations(ensembl_id)
    if not associations:
        print("ERROR: No disease associations found.")
        return
    print(f"      Found {len(associations)} disease associations.")

    print(f"[3/4] Matching to '{disease_name}'...")
    match = find_disease_match(associations, disease_name)

    if not match:
      print(f"      No exact match found for '{disease_name}'.")
      print("      Avoiding incorrect fallback to unrelated disease.")
      print("\nRESULT: LOW BIOLOGICAL RELEVANCE (No valid disease match)")
      return
    matched_disease = match["disease"]["name"]
    overall_score = match["score"]
    print(f"      Best match: '{matched_disease}' (score: {round(overall_score, 3)})")

    print("[4/4] Parsing evidence types...")
    evidence = parse_evidence_types(match.get("datatypeScores", []))
    for k, v in evidence.items():
        print(f"      {k}: {v}")

    assessment = rule_based_assessment(overall_score, evidence)


    print(f"\n{'='*60}")
    print(f"  FINAL REPORT")
    print(f"{'='*60}")
    print(f"  Protein       : {gene_symbol} - {full_name}")
    print(f"  Disease       : {matched_disease}")
    print(f"  Overall Score : {assessment['overall_score']}/1.0")
    print(f"  Verdict       : {assessment['verdict']}")

    if assessment["positive_signals"]:
        print(f"\n  Positive Signals:")
        for s in assessment["positive_signals"]:
            print(f"     + {s}")

    if assessment["warning_signals"]:
        print(f"\n  Warning Signals:")
        for s in assessment["warning_signals"]:
            print(f"     ! {s}")



if __name__ == "__main__":
    biology_agent("BRAF", "melanoma")

    # More to try:
    # biology_agent("EGFR", "breast cancer")
    # biology_agent("BRAF", "melanoma")
    # biology_agent("KRAS", "pancreatic cancer")
    # "GAPDH", "diabetes"